version: '3.7'

services:
  postgres:
    image: postgres:15.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - './docker-postgres-init.sql:/docker-entrypoint-initdb.d/docker-postgres-init.sql'
    networks:
      - postgres-boss-backup

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_PORT=9000
      - MINIO_USE_SSL=0
      - MINIO_BROWSER_REDIRECT_URL=http://localhost:9001
      - MINIO_SERVER_URL=http://localhost:9000
    volumes:
     - /var/data/minio:/data
    command:  minio server /data --console-address ":9001"
    networks:
      - postgres-boss-backup

networks:
  postgres-boss-backup:
